structure(list(url = "https://api.ohsome.org/v1/elements/amount", 
    status_code = 404L, headers = structure(list(date = "Tue, 22 Jun 2021 15:13:36 GMT", 
        server = "Apache/2.4.29 (Ubuntu)", `access-control-allow-origin` = "*", 
        `access-control-allow-methods` = "POST, GET", `access-control-max-age` = "3600", 
        `access-control-allow-credentials` = "true", `access-control-allow-headers` = "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization", 
        `content-disposition` = "attachment;filename=ohsome.csv", 
        `content-type` = "application/json;charset=UTF-8", `content-encoding` = "gzip", 
        vary = "Accept-Encoding", `cache-control` = "max-age=0, no-store", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 22 Jun 2021 15:13:36 GMT", 
            server = "Apache/2.4.29 (Ubuntu)", `access-control-allow-origin` = "*", 
            `access-control-allow-methods` = "POST, GET", `access-control-max-age` = "3600", 
            `access-control-allow-credentials` = "true", `access-control-allow-headers` = "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization", 
            `content-disposition` = "attachment;filename=ohsome.csv", 
            `content-type` = "application/json;charset=UTF-8", 
            `content-encoding` = "gzip", vary = "Accept-Encoding", 
            `cache-control` = "max-age=0, no-store", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2021-06-22T15:13:36.122+0000\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"message\" : \"No message available\",\n  \"path\" : \"/elements/amount\"\n}"), 
    date = structure(1624374816, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.015879, 
    connect = 0.113829, pretransfer = 0.155543, starttransfer = 0, 
    total = 0.248149)), class = "response")
