structure(list(url = "https://api.ohsome.org/v1/elements/count", 
    status_code = 200L, headers = structure(list(date = "Wed, 30 Jun 2021 09:43:58 GMT", 
        server = "Apache/2.4.29 (Ubuntu)", `access-control-allow-origin` = "*", 
        `access-control-allow-methods` = "POST, GET", `access-control-max-age` = "3600", 
        `access-control-allow-credentials` = "true", `access-control-allow-headers` = "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization", 
        `content-disposition` = "attachment;filename=ohsome.csv", 
        `content-type` = "text/csv;charset=UTF-8", `content-encoding` = "gzip", 
        vary = "Accept-Encoding", `cache-control` = "max-age=0, no-store", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Wed, 30 Jun 2021 09:43:58 GMT", 
            server = "Apache/2.4.29 (Ubuntu)", `access-control-allow-origin` = "*", 
            `access-control-allow-methods` = "POST, GET", `access-control-max-age` = "3600", 
            `access-control-allow-credentials` = "true", `access-control-allow-headers` = "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization", 
            `content-disposition` = "attachment;filename=ohsome.csv", 
            `content-type` = "text/csv;charset=UTF-8", `content-encoding` = "gzip", 
            vary = "Accept-Encoding", `cache-control` = "max-age=0, no-store", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("# Copyright URL: https://ohsome.org/copyrights\n# Copyright Text: © OpenStreetMap contributors\n# API Version: 1.5.0\ntimestamp;value\n\"2021-06-20T20:00:00Z\";\"24.0\"\n"), 
    date = structure(1625046238, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.009209, 
    connect = 0.09096, pretransfer = 0.142889, starttransfer = 0, 
    total = 10.544062)), class = "response")
