structure(list(url = "https://api.ohsome.org/404/metadata", status_code = 404L, 
    headers = structure(list(date = "Wed, 16 Jun 2021 07:38:04 GMT", 
        server = "Apache/2.4.29 (Ubuntu)", `content-length` = "277", 
        `content-type` = "text/html; charset=iso-8859-1"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(date = "Wed, 16 Jun 2021 07:38:04 GMT", 
            server = "Apache/2.4.29 (Ubuntu)", location = "https://api.ohsome.org/404/metadata", 
            `content-length` = "323", `content-type` = "text/html; charset=iso-8859-1"), class = c("insensitive", 
        "list"))), list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Wed, 16 Jun 2021 07:38:04 GMT", 
            server = "Apache/2.4.29 (Ubuntu)", `content-length` = "277", 
            `content-type` = "text/html; charset=iso-8859-1"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n<hr>\n<address>Apache/2.4.29 (Ubuntu) Server at api.ohsome.org Port 443</address>\n</body></html>\n"), 
    date = structure(1623829084, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.105752, namelookup = 0.008729, 
    connect = 0.128672, pretransfer = 0.158497, starttransfer = 0.220432, 
    total = 0.220477)), class = "response")
